### ISSUE TITLE
[New functionnality] Detect required spaces before operand and keywords

### ISSUE THREAD

**Issue by GNUletik** [casimir/epinorme#10]
Examples : 
 - var=var+1;
 - if(test==test);

**Comment by casimir** [comment]
Ok I'm on it but this is a tricky one. Composite operators (== isn't = x 2) are awful to match...

**Comment by casimir** [comment]
It should be _mostly_ implemented in `0.4.0` version. I'll close this for now but feel free to reopen if needed.
